export const LOAD_PAGE = 'LOAD_PAGE';
export const GET_PAGE = 'GET_PAGE';

// login
export const SET_LOGIN = 'SET_LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_RESET_ERROR = 'LOGIN_RESET_ERROR';

// registration;
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_RESET_DATA = 'REGISTRATION_RESET_DATA';

// meta
export const GET_META = 'GET_META';
export const SET_META = 'SET_META';

// page
export const GET_PAGE_DATA = 'GET_PAGE_DATA';
export const SET_PAGE_DATA = 'SET_PAGE_DATA';

// footer
export const GET_FOOTER = 'GET_FOOTER';
export const SET_FOOTER = 'SET_FOOTER';

// loader
export const GET_LOADER = 'GET_LOADER';
export const SET_LOADER = 'SET_LOADER';
export const GET_LOADER_PAGE = 'GET_LOADER_PAGE';
export const SET_LOADER_PAGE = 'SET_LOADER_PAGE';

// words
export const WORD_SET_LIST = 'WORD_SET_LIST';

export const WORD_ITEM_REQUEST = 'WORD_ITEM_REQUEST';
export const WORD_ITEM_SUCCESS = 'WORD_ITEM_SUCCESS';
export const WORD_ITEM_ERROR = 'WORD_ITEM_ERROR';

export const WORDS_PAGE = 'WORDS_PAGE';
export const WORDS_PAGE_NUM = 'WORDS_PAGE_NUM';
export const WORDS_PAGE_SET_LANG = 'WORDS_PAGE_SET_LANG';
export const WORDS_PAGE_SET_POS = 'WORDS_PAGE_SET_POS';

export const WORD_PAGE_SET_DATA = 'WORD_PAGE_SET_DATA';

// proverbs
export const LOAD_PROVERB = 'LOAD_PROVERB';

// online users
export const LOAD_USERS_ONLINE = 'LOAD_USERS_ONLINE';

// profile;
export const PROFILE_FORM_REQUEST = 'PROFILE_FORM_REQUEST';
export const PROFILE_FORM_SUCCESS = 'PROFILE_FORM_SUCCESS';
export const PROFILE_FORM_ERROR = 'PROFILE_FORM_ERROR';

// modal window
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_REQUEST = 'MODAL_REQUEST';
export const MODAL_SUCCESS = 'MODAL_SUCCESS';
export const MODAL_ERROR = 'MODAL_ERROR';
export const MODAL_SET_HEADER = 'MODAL_SET_HEADER';
export const MODAL_SET_CONTENT = 'MODAL_SET_CONTENT';

export const LEARNING_WRITE_DATA = 'LEARNING_WRITE_DATA';
export const LEARNING_WRITE_SET_LOADING = 'LEARNING_WRITE_SET_LOADING';

export const TESTYOURSELF_DATA = 'TESTYOURSELF_DATA';
export const TESTYOURSELF_REQUEST = 'TESTYOURSELF_REQUEST';
export const TESTYOURSELF_SUCCESS = 'TESTYOURSELF_SUCCESS';
export const TESTYOURSELF_ERROR = 'TESTYOURSELF_ERROR';

// statistic
export const STATISTIC_SET_DATA = 'STATISTIC_SET_DATA';

// lyrics
export const LYRIC_SET_LIST = 'LYRIC_SET_LIST';
export const LYRIC_SET_ITEM = 'LYRIC_SET_ITEM';

// lessons
export const LESSON_SET_LIST = 'LESSON_SET_LIST';
export const LESSON_SET_ITEM = 'LESSON_SET_ITEM'

// player
export const PLAYER_GET_SONGS_LIST_REQUEST = 'PLAYER_GET_SONGS_LIST_REQUEST';
export const PLAYER_GET_SONGS_LIST_SUCCESS = 'PLAYER_GET_SONGS_LIST_SUCCESS';
export const PLAYER_GET_SONGS_LIST_ERROR = 'PLAYER_GET_SONGS_LIST_ERROR';
export const PLAYER_SHOW_SONGS_LIST = 'PLAYER_SHOW_SONGS_LIST';
export const PLAYER_CLOSE_SONGS_LIST = 'PLAYER_CLOSE_SONGS_LIST';

export const PLAYER_GET_SONG_REQUEST = 'PLAYER_GET_SONG_REQUEST';
export const PLAYER_GET_SONG_SUCCESS = 'PLAYER_GET_SONG_SUCCESS';
export const PLAYER_GET_SONG_ERROR = 'PLAYER_GET_SONG_ERROR';
export const PLAYER_CLOSE_SONG = 'PLAYER_CLOSE_SONG';
export const PLAYER_SHOW_SONG = 'PLAYER_SHOW_SONG';

export const PLAYER_LOADING_OPEN_TRACK_REQUEST = 'PLAYER_LOADING_OPEN_TRACK_REQUEST';
export const PLAYER_LOADING_OPEN_TRACK_SUCCESS = 'PLAYER_LOADING_OPEN_TRACK_SUCCESS';
export const PLAYER_LOADING_OPEN_TRACK_ERROR = 'PLAYER_LOADING_OPEN_TRACK_ERROR';
export const PLAYER_LOADING_OPEN_TRACK_SET_LOADING = 'PLAYER_LOADING_OPEN_TRACK_SET_LOADING';

export const PLAYER_INIT_LYRICS = 'PLAYER_INIT_LYRICS';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_REMOVE = 'SEARCH_REMOVE';

// forum
export const FORUM_SET_FORUM = 'FORUM_SET_FORUM';
export const FORUM_SET_FORUMS_LIST = 'FORUM_SET_FORUMS_LIST';
export const FORUM_SET_TOPIC = 'FORUM_SET_TOPIC';
export const FORUM_SET_TOPICS_LIST = 'FORUM_SET_TOPICS_LIST';
export const FORUM_SET_MESSAGES_LIST = 'FORUM_SET_MESSAGES_LIST';

export const FORUM_QUOTE_ADD = 'FORUM_QUOTE_ADD';
export const FORUM_QUOTS_REMOVE = 'FORUM_QUOTS_REMOVE';

// index
export const INDEX_SET_FORUM = 'INDEX_SET_FORUM';

// user
export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';

// user info
export const USER_INFO_SET_INFO = 'USER_INFO_SET_INFO';

// users list
export const USERS_LIST_SET_DATA = 'USERS_LIST_SET_DATA';

// grammar
export const GRAMMAR_SET_LIST = 'GRAMMAR_SET_LIST';
export const GRAMMAR_SET_ITEM = 'GRAMMAR_SET_ITEM';

// error
export const ERROR_PAGE = 'ERROR_PAGE';
export const ERROR_PAGE_REMOVE = 'ERROR_PAGE_REMOVE';
